/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.osfprieto;

import Jama.Matrix;
import CryptographyAlgorithms.AffineCipherAlgorithm;
import CryptographyAlgorithms.MonoalphabeticCipherAlgorithm;
import CryptographyAlgorithms.PermutacionCipherAlgorithm;
import CryptographyAlgorithms.RSACipherAlgorithm;
import CryptographyAlgorithms.ShiftCipherAlgorithm;
import CryptographyAlgorithms.VigenereCipherAlgorithm;
import HillCipherAlgorithm.Hill;
import HillCipherAlgorithm.HillKey;

/**
 *
 * @author OmarSimónFrancisco
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form OmarJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        buttonDecipherShift = new javax.swing.JButton();
        spinnerKeyShift = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        buttonCipherShift = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clearTextAreaShift = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        cipherTextAreaShift = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        clearTextAreaAfin = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        cipherTextAreaAfin = new javax.swing.JTextArea();
        buttonCipherAfin = new javax.swing.JButton();
        buttonDecipherAfin = new javax.swing.JButton();
        spinnerKeyAfinA = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinnerKeyAfinB = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        clearTextAreaVigenere = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        cipherTextAreaVigenere = new javax.swing.JTextArea();
        buttonCipherVigenere = new javax.swing.JButton();
        buttonDecipherVigenere = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textFieldVigenereKey = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        clearTextAreaSustitucion = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        cipherTextAreaSustitucion = new javax.swing.JTextArea();
        buttonCipherSustitucion = new javax.swing.JButton();
        buttonDecipherSustitucion = new javax.swing.JButton();
        textFieldSustitucionKey = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        clearTextAreaPermutacion = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        cipherTextAreaPermutacion = new javax.swing.JTextArea();
        buttonCipherPermutacion = new javax.swing.JButton();
        buttonDecipherPermutacion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        textFieldPermutacionKey = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        clearTextAreaHill = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        cipherTextAreaHill = new javax.swing.JTextArea();
        buttonCipherHill = new javax.swing.JButton();
        buttonDecipherHill = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        textAreaHillMatrix = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        buttonDecipherRSA = new javax.swing.JButton();
        buttonCipherRSA = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        clearTextAreaRSA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cipherTextAreaRSA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelRSAD = new javax.swing.JLabel();
        jLabelRSAFiN = new javax.swing.JLabel();
        jLabelRSAN = new javax.swing.JLabel();
        textFieldRSAP = new javax.swing.JTextField();
        textFieldRSAQ = new javax.swing.JTextField();
        textFieldRSAE = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonDecipherShift.setText("<-- Descifrar --");
        buttonDecipherShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherShiftActionPerformed(evt);
            }
        });

        jLabel1.setText("Translación - Llave para translación, número entre 0 y 26 que sea coprimo con 26");

        buttonCipherShift.setText("-- Cifrar -->");
        buttonCipherShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherShiftActionPerformed(evt);
            }
        });

        clearTextAreaShift.setColumns(20);
        clearTextAreaShift.setRows(5);
        clearTextAreaShift.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane2.setViewportView(clearTextAreaShift);

        cipherTextAreaShift.setColumns(20);
        cipherTextAreaShift.setRows(5);
        jScrollPane1.setViewportView(cipherTextAreaShift);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spinnerKeyShift, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonDecipherShift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonCipherShift, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerKeyShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonCipherShift)
                        .addGap(18, 18, 18)
                        .addComponent(buttonDecipherShift)))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Translación", jPanel2);

        clearTextAreaAfin.setColumns(20);
        clearTextAreaAfin.setRows(5);
        clearTextAreaAfin.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane5.setViewportView(clearTextAreaAfin);

        cipherTextAreaAfin.setColumns(20);
        cipherTextAreaAfin.setRows(5);
        jScrollPane6.setViewportView(cipherTextAreaAfin);

        buttonCipherAfin.setText("-- Cifrar -->");
        buttonCipherAfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherAfinActionPerformed(evt);
            }
        });

        buttonDecipherAfin.setText("<-- Descifrar --");
        buttonDecipherAfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherAfinActionPerformed(evt);
            }
        });

        spinnerKeyAfinA.setValue(15);

        jLabel8.setText("Key A (coprimo con 26)");

        jLabel9.setText("Key B");

        jLabel13.setText("E(x) = (Ax + B) mod 26");

        jLabel14.setText("D(y) = A^-1(x - B) mod 26");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerKeyAfinB, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerKeyAfinA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonDecipherAfin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCipherAfin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonCipherAfin)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(4, 4, 4)
                                .addComponent(buttonDecipherAfin))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(spinnerKeyAfinA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(spinnerKeyAfinB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                    .addGap(154, 154, 154)))
        );

        jTabbedPane1.addTab("Afín", jPanel3);

        clearTextAreaVigenere.setColumns(20);
        clearTextAreaVigenere.setRows(5);
        clearTextAreaVigenere.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane7.setViewportView(clearTextAreaVigenere);

        cipherTextAreaVigenere.setColumns(20);
        cipherTextAreaVigenere.setRows(5);
        jScrollPane8.setViewportView(cipherTextAreaVigenere);

        buttonCipherVigenere.setText("-- Cifrar -->");
        buttonCipherVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherVigenereActionPerformed(evt);
            }
        });

        buttonDecipherVigenere.setText("<-- Descifrar --");
        buttonDecipherVigenere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherVigenereActionPerformed(evt);
            }
        });

        jLabel10.setText("Palabra clave, sin espacios");

        textFieldVigenereKey.setText("clavesecreta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldVigenereKey, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonCipherVigenere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDecipherVigenere))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCipherVigenere)
                    .addComponent(jLabel10))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonDecipherVigenere))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(textFieldVigenereKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Vigenere", jPanel4);

        clearTextAreaSustitucion.setColumns(20);
        clearTextAreaSustitucion.setRows(5);
        clearTextAreaSustitucion.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane14.setViewportView(clearTextAreaSustitucion);

        cipherTextAreaSustitucion.setColumns(20);
        cipherTextAreaSustitucion.setRows(5);
        jScrollPane15.setViewportView(cipherTextAreaSustitucion);

        buttonCipherSustitucion.setText("-- Cifrar -->");
        buttonCipherSustitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherSustitucionActionPerformed(evt);
            }
        });

        buttonDecipherSustitucion.setText("<-- Descifrar --");
        buttonDecipherSustitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherSustitucionActionPerformed(evt);
            }
        });

        textFieldSustitucionKey.setText("zyxwvutsrqponmlkjihgfedcba");

        jLabel15.setText("Sustitución de texto, la A es reemplazada por el primer caracter y la z es reemplazada por el último. 26 caracteres alfabéticos sin repetir.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldSustitucionKey, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(404, 404, 404)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonCipherSustitucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDecipherSustitucion))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldSustitucionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addComponent(jScrollPane15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                    .addComponent(buttonCipherSustitucion)
                    .addGap(18, 18, 18)
                    .addComponent(buttonDecipherSustitucion)
                    .addGap(30, 30, 30)))
        );

        jTabbedPane1.addTab("Sustitución", jPanel1);

        clearTextAreaPermutacion.setColumns(20);
        clearTextAreaPermutacion.setRows(5);
        clearTextAreaPermutacion.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane9.setViewportView(clearTextAreaPermutacion);

        cipherTextAreaPermutacion.setColumns(20);
        cipherTextAreaPermutacion.setRows(5);
        jScrollPane10.setViewportView(cipherTextAreaPermutacion);

        buttonCipherPermutacion.setText("-- Cifrar -->");
        buttonCipherPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherPermutacionActionPerformed(evt);
            }
        });

        buttonDecipherPermutacion.setText("<-- Descifrar --");
        buttonDecipherPermutacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherPermutacionActionPerformed(evt);
            }
        });

        jLabel11.setText("Clave: orden permutación a ejecutar, números separados por comas e indexado desde 0.");

        textFieldPermutacionKey.setText("0, 3, 1, 2, 5, 4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(textFieldPermutacionKey, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonDecipherPermutacion)
                            .addComponent(buttonCipherPermutacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(textFieldPermutacionKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(buttonCipherPermutacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDecipherPermutacion)
                        .addGap(23, 23, 23))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addComponent(jScrollPane10))
                    .addContainerGap(150, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Permutación", jPanel6);

        clearTextAreaHill.setColumns(20);
        clearTextAreaHill.setRows(5);
        clearTextAreaHill.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane11.setViewportView(clearTextAreaHill);

        cipherTextAreaHill.setColumns(20);
        cipherTextAreaHill.setRows(5);
        jScrollPane12.setViewportView(cipherTextAreaHill);

        buttonCipherHill.setText("-- Cifrar -->");
        buttonCipherHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherHillActionPerformed(evt);
            }
        });

        buttonDecipherHill.setText("<-- Descifrar --");
        buttonDecipherHill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherHillActionPerformed(evt);
            }
        });

        textAreaHillMatrix.setColumns(20);
        textAreaHillMatrix.setRows(5);
        textAreaHillMatrix.setText("11 6 8\n0 3 14\n24 0 9");
        jScrollPane13.setViewportView(textAreaHillMatrix);

        jLabel12.setText("Matriz de llave de Hill, debe ser una matriz cuadrada, los números deben estar separados por espacios y debe haber una filla por línea. La matriz debe ser inversible.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCipherHill, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDecipherHill)))
                    .addComponent(jLabel12))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jScrollPane12))
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(buttonCipherHill)
                        .addGap(26, 26, 26)
                        .addComponent(buttonDecipherHill)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hill", jPanel5);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hill imágenes", jPanel9);

        buttonDecipherRSA.setText("<-- Descifrar --");
        buttonDecipherRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecipherRSAActionPerformed(evt);
            }
        });

        buttonCipherRSA.setText("-- Cifrar -->");
        buttonCipherRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCipherRSAActionPerformed(evt);
            }
        });

        clearTextAreaRSA.setColumns(20);
        clearTextAreaRSA.setRows(5);
        clearTextAreaRSA.setText("Omar Simon Francisco Prieto Chacon");
        jScrollPane3.setViewportView(clearTextAreaRSA);

        cipherTextAreaRSA.setColumns(20);
        cipherTextAreaRSA.setRows(5);
        jScrollPane4.setViewportView(cipherTextAreaRSA);

        jLabel2.setText("P (primo)");
        jLabel2.setToolTipText("Número primo para generación del módulo a utilizar junto con Q");

        jLabel3.setText("Q (primo)");
        jLabel3.setToolTipText("Número primo para generación del módulo a utilizar junto con P");

        jLabel4.setText("E (pública, coprimo a Euler(N))");
        jLabel4.setToolTipText("Llave pública de cifrado");

        jLabel5.setText("N (pública)");
        jLabel5.setToolTipText("P*Q");

        jLabel6.setText("D");
        jLabel6.setToolTipText("Llave privada para descifrado.");

        jLabel7.setText("Euler(N)");
        jLabel7.setToolTipText("Número primo para generación del módulo a utilizar junto con P");

        jLabelRSAD.setText("D");
        jLabelRSAD.setToolTipText("Llave privada para descifrado.");

        jLabelRSAFiN.setText("Euler(N)");
        jLabelRSAFiN.setToolTipText("Número primo para generación del módulo a utilizar junto con P");

        jLabelRSAN.setText("N");
        jLabelRSAN.setToolTipText("P*Q");

        textFieldRSAP.setText("89");
        textFieldRSAP.setToolTipText("Prime number");

        textFieldRSAQ.setText("97");
        textFieldRSAQ.setToolTipText("Prime number");

        textFieldRSAE.setText("13");
        textFieldRSAE.setToolTipText("Prime number");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldRSAQ, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRSAE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldRSAP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonDecipherRSA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCipherRSA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRSAN)
                    .addComponent(jLabelRSAFiN)
                    .addComponent(jLabelRSAD))
                .addGap(205, 205, 205))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textFieldRSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldRSAQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldRSAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(buttonCipherRSA)
                                .addGap(40, 40, 40)
                                .addComponent(buttonDecipherRSA))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabelRSAN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelRSAFiN)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabelRSAD)))))))
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("RSA", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCipherRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherRSAActionPerformed
        if(clearTextAreaRSA.getText().length()>0){
            Long[] keys = new Long[3];
            keys[0] = Long.parseLong(textFieldRSAP.getText());
            keys[1] = Long.parseLong(textFieldRSAQ.getText());
            keys[2] = Long.parseLong(textFieldRSAE.getText());
            rsa.setKeys(keys);
            jLabelRSAN.setText(rsa.getN()+"");
            jLabelRSAFiN.setText(rsa.getFiN()+"");
            jLabelRSAD.setText(rsa.getD()+"");

            rsa.setClearData(clearTextAreaRSA.getText());
            rsa.encrypt();
            cipherTextAreaRSA.setText((String) rsa.getCipherData());
        }
    }//GEN-LAST:event_buttonCipherRSAActionPerformed

    private void buttonDecipherRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherRSAActionPerformed
        if(cipherTextAreaRSA.getText().length()>0){
            Long[] keys = new Long[3];
            keys[0] = Long.parseLong(textFieldRSAP.getText());
            keys[1] = Long.parseLong(textFieldRSAQ.getText());
            keys[2] = Long.parseLong(textFieldRSAE.getText());
            rsa.setKeys(keys);
            jLabelRSAN.setText(rsa.getN()+"");
            jLabelRSAFiN.setText(rsa.getFiN()+"");
            jLabelRSAD.setText(rsa.getD()+"");

            rsa.setCipherData(cipherTextAreaRSA.getText());
            rsa.decrypt();
            clearTextAreaRSA.setText((String) rsa.getClearData());
        }
    }//GEN-LAST:event_buttonDecipherRSAActionPerformed

    private void buttonDecipherVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherVigenereActionPerformed
        VigenereCipherAlgorithm vigenere = new VigenereCipherAlgorithm();
        vigenere.setKeys(textFieldVigenereKey.getText());
        vigenere.setCipherData(cipherTextAreaVigenere.getText().toLowerCase());
        vigenere.decrypt();
        clearTextAreaVigenere.setText((String) vigenere.getClearData());
    }//GEN-LAST:event_buttonDecipherVigenereActionPerformed

    private void buttonCipherVigenereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherVigenereActionPerformed
        VigenereCipherAlgorithm vigenere = new VigenereCipherAlgorithm();
        vigenere.setKeys(textFieldVigenereKey.getText());
        vigenere.setClearData(clearTextAreaVigenere.getText());
        vigenere.encrypt();
        cipherTextAreaVigenere.setText((String) vigenere.getCipherData());
    }//GEN-LAST:event_buttonCipherVigenereActionPerformed

    private void buttonDecipherAfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherAfinActionPerformed
        AffineCipherAlgorithm afinCipher = new AffineCipherAlgorithm();
        afinCipher.setFirstKey((Integer) spinnerKeyAfinA.getValue());
        afinCipher.setSecondKey((Integer) spinnerKeyAfinB.getValue());
        afinCipher.setCipherText(cipherTextAreaAfin.getText().toLowerCase());
        afinCipher.decryp();
        clearTextAreaAfin.setText(afinCipher.getPlainText());
    }//GEN-LAST:event_buttonDecipherAfinActionPerformed

    private void buttonCipherAfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherAfinActionPerformed
        AffineCipherAlgorithm afinCipher = new AffineCipherAlgorithm();
        afinCipher.setFirstKey((Integer) spinnerKeyAfinA.getValue());
        afinCipher.setSecondKey((Integer) spinnerKeyAfinB.getValue());
        afinCipher.setPlainText(clearTextAreaAfin.getText().toLowerCase());
        afinCipher.encryp();
        cipherTextAreaAfin.setText(afinCipher.getCipherText().toUpperCase());
    }//GEN-LAST:event_buttonCipherAfinActionPerformed

    private void buttonCipherShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherShiftActionPerformed
        shift.setKeys(""+spinnerKeyShift.getValue());
        shift.setClearData(clearTextAreaShift.getText());
        shift.encrypt();
        cipherTextAreaShift.setText((String)shift.getCipherData());
    }//GEN-LAST:event_buttonCipherShiftActionPerformed

    private void buttonDecipherShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherShiftActionPerformed
        shift.setKeys(""+spinnerKeyShift.getValue());
        shift.setCipherData(cipherTextAreaShift.getText());
        shift.decrypt();
        clearTextAreaShift.setText((String)shift.getClearData());
    }//GEN-LAST:event_buttonDecipherShiftActionPerformed

    private void buttonCipherPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherPermutacionActionPerformed
        PermutacionCipherAlgorithm permutacion = new PermutacionCipherAlgorithm();
        permutacion.setKeys(textFieldPermutacionKey.getText());
        permutacion.setClearData(clearTextAreaPermutacion.getText());
        permutacion.encrypt();
        cipherTextAreaPermutacion.setText((String)permutacion.getCipherData());
    }//GEN-LAST:event_buttonCipherPermutacionActionPerformed

    private void buttonDecipherPermutacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherPermutacionActionPerformed
        PermutacionCipherAlgorithm permutacion = new PermutacionCipherAlgorithm();
        permutacion.setKeys(textFieldPermutacionKey.getText());
        permutacion.setCipherData(cipherTextAreaPermutacion.getText());
        permutacion.decrypt();
        clearTextAreaPermutacion.setText((String)permutacion.getClearData());
    }//GEN-LAST:event_buttonDecipherPermutacionActionPerformed

    private void buttonCipherHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherHillActionPerformed

        String matrixKeyText = textAreaHillMatrix.getText();
        String matrixTextLines[] = matrixKeyText.split("\n");
        int m = matrixTextLines.length;
        int key[][] = new int[m][m];
        
        for(int i=0;i<m;i++){
            String tokens[] = matrixTextLines[i].split(" ");
            for(int j=0;j<m;j++)
                key[i][j] = Integer.parseInt(tokens[j]);
        }
        
        
        HillKey hKey = new HillKey(26, m, null, key);
        hill.setKeys(hKey);
        hill.setClearData(hKey.getTextData(clearTextAreaHill.getText().toLowerCase()));
        hill.encrypt();
        
        String secret = "";
        Matrix[] secretData = (Matrix[])hill.getCipherData();
        for (int i = 0; i < secretData.length; i++) {
            for (int j = 0; j < m; j++) {
                int v = (int)secretData[i].get(0, j);
                secret += (char)(v+'a');
            }
        }
        
        cipherTextAreaHill.setText(secret);
    }//GEN-LAST:event_buttonCipherHillActionPerformed

    private void buttonDecipherHillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherHillActionPerformed
        String matrixKeyText = textAreaHillMatrix.getText();
        String matrixTextLines[] = matrixKeyText.split("\n");
        int m = matrixTextLines.length;
        int key[][] = new int[m][m];
        
        for(int i=0;i<m;i++){
            String tokens[] = matrixTextLines[i].split(" ");
            for(int j=0;j<m;j++)
                key[i][j] = Integer.parseInt(tokens[j]);
        }
        
        HillKey hKey = new HillKey(26, m, null, key);
        hill.setKeys(hKey);
        
        hill.setCipherData(hKey.getTextData(cipherTextAreaHill.getText()));
        hill.decrypt();
        Matrix[] secretData = (Matrix[])hill.getClearData();
        String secret = "";
        for (int i = 0; i < secretData.length; i++) {
            for (int j = 0; j < m; j++) {
                int v = (int)secretData[i].get(0, j);
                secret += (char)(v+'a');
            }
        }
        clearTextAreaHill.setText(secret);
    }//GEN-LAST:event_buttonDecipherHillActionPerformed

    private void buttonCipherSustitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCipherSustitucionActionPerformed
        MonoalphabeticCipherAlgorithm cipher = new MonoalphabeticCipherAlgorithm();
        cipher.convert(textFieldSustitucionKey.getText());
        cipher.setPlainText(clearTextAreaSustitucion.getText().toLowerCase());
        cipher.encrypt();
        cipherTextAreaSustitucion.setText(cipher.getCipherText().toUpperCase());
    }//GEN-LAST:event_buttonCipherSustitucionActionPerformed

    private void buttonDecipherSustitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecipherSustitucionActionPerformed
        MonoalphabeticCipherAlgorithm cipher = new MonoalphabeticCipherAlgorithm();
        cipher.setCipherText(cipherTextAreaSustitucion.getText().toLowerCase());
        cipher.setKey(textFieldSustitucionKey.getText());
        cipher.convert(textFieldSustitucionKey.getText());
        cipher.decryp();
        clearTextAreaSustitucion.setText(cipher.getPlainText().toLowerCase());
    }//GEN-LAST:event_buttonDecipherSustitucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private ShiftCipherAlgorithm shift = new ShiftCipherAlgorithm();
    private RSACipherAlgorithm rsa = new RSACipherAlgorithm();
    private Hill hill = new Hill();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCipherAfin;
    private javax.swing.JButton buttonCipherHill;
    private javax.swing.JButton buttonCipherPermutacion;
    private javax.swing.JButton buttonCipherRSA;
    private javax.swing.JButton buttonCipherShift;
    private javax.swing.JButton buttonCipherSustitucion;
    private javax.swing.JButton buttonCipherVigenere;
    private javax.swing.JButton buttonDecipherAfin;
    private javax.swing.JButton buttonDecipherHill;
    private javax.swing.JButton buttonDecipherPermutacion;
    private javax.swing.JButton buttonDecipherRSA;
    private javax.swing.JButton buttonDecipherShift;
    private javax.swing.JButton buttonDecipherSustitucion;
    private javax.swing.JButton buttonDecipherVigenere;
    private javax.swing.JTextArea cipherTextAreaAfin;
    private javax.swing.JTextArea cipherTextAreaHill;
    private javax.swing.JTextArea cipherTextAreaPermutacion;
    private javax.swing.JTextArea cipherTextAreaRSA;
    private javax.swing.JTextArea cipherTextAreaShift;
    private javax.swing.JTextArea cipherTextAreaSustitucion;
    private javax.swing.JTextArea cipherTextAreaVigenere;
    private javax.swing.JTextArea clearTextAreaAfin;
    private javax.swing.JTextArea clearTextAreaHill;
    private javax.swing.JTextArea clearTextAreaPermutacion;
    private javax.swing.JTextArea clearTextAreaRSA;
    private javax.swing.JTextArea clearTextAreaShift;
    private javax.swing.JTextArea clearTextAreaSustitucion;
    private javax.swing.JTextArea clearTextAreaVigenere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRSAD;
    private javax.swing.JLabel jLabelRSAFiN;
    private javax.swing.JLabel jLabelRSAN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spinnerKeyAfinA;
    private javax.swing.JSpinner spinnerKeyAfinB;
    private javax.swing.JSpinner spinnerKeyShift;
    private javax.swing.JTextArea textAreaHillMatrix;
    private javax.swing.JTextField textFieldPermutacionKey;
    private javax.swing.JTextField textFieldRSAE;
    private javax.swing.JTextField textFieldRSAP;
    private javax.swing.JTextField textFieldRSAQ;
    private javax.swing.JTextField textFieldSustitucionKey;
    private javax.swing.JTextField textFieldVigenereKey;
    // End of variables declaration//GEN-END:variables
}
